[package]
name = "globant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.17.1"
rand = "0.8.4"
rand_pcg = "0.3.1"
rand_seeder = "0.2.2"
to-binary = "0.4.0"
